### ISSUE TITLE
Dynamics: Allow for tether unreel

### ISSUE THREAD

**Issue by cjthomas24** [CUGravity/ACS-Full-System-Simulation#21]
model with hydraulic piston system?

**Comment by dtkaiser** [comment]
A test model has been added which demonstrates the ability to dynamically control distance between two frames. BUT there is the problem that it does so through forced motion or a forcing function. Neither of which are realistic for our model which simply lets out a certain amount of tether and allows it to become taught unhindered. An intermediary block will be needed to simulate the unreeling motor in the Dynamics block. This will allow us to control the unreeling motion to be proportional to the centripetal acceleration induced force outwards on the tether. For now though the directly controlled motion should be sufficient.
